# Generated by Django 4.2.4 on 2023-08-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_alter_user_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='transcript',
            field=models.TextField(default='Nothing'),
            preserve_default=False,
        ),
    ]
