# Generated by Django 4.2.4 on 2023-08-12 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_meeting_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='transcript',
            field=models.TextField(default='The transcript for this field is currently being generated...'),
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='grievances', validators=[feedback.models.validate_audio], verbose_name='Grievance')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
