# Generated by Django 4.2.4 on 2023-08-12 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_alter_meeting_transcript_grievance'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 13)),
        ),
    ]
