# Generated by Django 4.2.4 on 2023-08-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_grievance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
