# Generated by Django 4.2.4 on 2023-08-12 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_grievance_important'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.village')),
            ],
        ),
    ]
