# Generated by Django 4.2.4 on 2023-08-13 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_schedulemeeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='transcript',
        ),
    ]
