# Generated by Django 4.2.4 on 2023-10-17 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0014_remove_meeting_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_code',
            field=models.BigIntegerField(default=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grievance',
            name='date',
            field=models.DateField(default=datetime.date(2023, 10, 17)),
        ),
    ]
