# Generated by Django 4.2.4 on 2023-10-17 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0014_remove_meeting_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='date',
            field=models.DateField(default=datetime.date(2023, 10, 17)),
        ),
    ]
