# Generated by Django 4.2.4 on 2023-10-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0015_user_user_code_alter_grievance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_code',
            field=models.BigIntegerField(),
        ),
    ]
