# Generated by Django 4.2.4 on 2023-11-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0015_alter_grievance_date'),
        ('feedback', '0017_alter_user_user_code'),
    ]

    operations = [
    ]
