# Generated by Django 4.2.4 on 2023-11-14 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0018_merge_20231114_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='district',
        ),
        migrations.AlterField(
            model_name='grievance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='feedback.district'),
        ),
        migrations.AlterField(
            model_name='user',
            name='village',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='sub_district', chained_model_field='sub_district', null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.village'),
        ),
        migrations.CreateModel(
            name='SubDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sub-District name')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.district')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='sub_district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='district', chained_model_field='district', default=0, on_delete=django.db.models.deletion.CASCADE, to='feedback.subdistrict'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='village',
            name='sub_district',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='feedback.subdistrict'),
            preserve_default=False,
        ),
    ]
