# Generated by Django 4.2.4 on 2023-11-28 15:33

from django.db import migrations


def add_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    Group.objects.create(name="Village Admin")
    Group.objects.create(name="Villager")
    Group.objects.create(name="District Admin")


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0020_auto_20231114_1403"),
    ]

    operations = [
        migrations.RunPython(add_groups)
    ]
