# Generated by Django 4.2.4 on 2025-04-04 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0022_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfHelpGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='SHG name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('pool', models.IntegerField(default=0)),
                ('min_contribution', models.IntegerField(default=0, verbose_name='Minimum Contribution for new users')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SHGContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('shg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.selfhelpgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'shg')},
            },
        ),
        migrations.AddField(
            model_name='selfhelpgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', through='feedback.SHGContribution', to=settings.AUTH_USER_MODEL),
        ),
    ]
