# Generated by Django 4.2.4 on 2025-04-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0023_selfhelpgroup_shgcontribution_selfhelpgroup_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfhelpgroup',
            name='target',
            field=models.CharField(blank=True, max_length=200, verbose_name='Target members'),
        ),
    ]
