# Generated by Django 4.2.4 on 2025-04-10 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0024_selfhelpgroup_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfhelpgroup',
            name='interest_model',
            field=models.IntegerField(choices=[(0, 'Flat Rate'), (1, 'Declining Balance'), (2, 'Reducing Flat Rate'), (3, 'EMI'), (4, 'Compound')], default=0),
        ),
        migrations.AddField(
            model_name='shgcontribution',
            name='role',
            field=models.IntegerField(choices=[(1, 'Administrator'), (2, 'Member')], default=2),
        ),
        migrations.CreateModel(
            name='SHGLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.IntegerField(verbose_name='Principal')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('purpose', models.TextField(verbose_name='Purpose')),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(verbose_name='Duration (in months)')),
                ('repayment_freq', models.IntegerField(choices=[(0, 'Biweekly'), (1, 'Weekly'), (2, 'Monthly'), (3, 'Quarterly')], default=2)),
                ('interest_rate', models.FloatField(verbose_name='Annual Interest Rate')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected'), (3, 'Completed'), (4, 'Defaulted')], default=0)),
                ('amortization_schedule', models.JSONField(blank=True, default=list)),
                ('shg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.selfhelpgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
