# Generated by Django 4.2.4 on 2025-04-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0025_selfhelpgroup_interest_model_shgcontribution_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shgloan',
            name='total_payable',
            field=models.FloatField(default=0, verbose_name='Total Payable'),
        ),
        migrations.AlterField(
            model_name='shgloan',
            name='principal',
            field=models.FloatField(verbose_name='Principal'),
        ),
        migrations.AlterField(
            model_name='shgloan',
            name='repayment_freq',
            field=models.IntegerField(choices=[(0, 'Biweekly'), (1, 'Weekly'), (2, 'Monthly'), (3, 'Quarterly')], default=2, verbose_name='Repayment Frequency'),
        ),
    ]
